# blog nexos migracion
#### Materiales para el analisis para el blog sobre migracion para la revista Nexos.

<details>
    <summary><strong>Meta</strong></summary>
    "La meta de este notebook es recrear la figura X del reporte XYZ ..."
    <ul>
        <li> Metas mensurables </li>
        <li> Ej 1: Identificar <i>variables de interes en el conjunto de datos <strong>nombre_chido_de_conjunto_de_datos.csv</strong></i> </li>
        <li> Ej 2: Crear un <i>dataset trabajable</i> de los datos en bruto.</li>
    </ul>
</details>

<details>
    <summary><strong>Contexto</strong></summary>
    Contexto en este momento (por ejemplo, "hemos descargado datos sin procesar de <strong><i>website.com</i> </strong> y ahora estamos en el proceso de crear un masterfile").
    <li> ¿Cuál es el objetivo final de este proyecto? </li>
    <li> ¿Qué estamos tratando de recrear? ¿Dónde estamos en el proceso? </li>
    <li> Cualquier enlace a documentación / figuras. </li>
</details>

In [18]:
import pandas as pd
from zipfile import ZipFile
from pathlib import Path
from herramientas import arbol
from datetime import datetime as dt
hoy = dt.today().strftime("%d-%b-%y")

hoy

'10-Jul-19'

In [19]:
DATOS_BRUTOS = Path("../datos/brutos/")
DATOS_INTERINOS = Path("../datos/interinos/")
DATOS_PROCESADOS = Path("../datos/procesados/")
DATOS_EXTERNOS = Path("../datos/externos/")

In [20]:
arbol(DATOS_BRUTOS)

+ ..\datos\brutos
    + base_datos_enadid18_csv.zip
    + conjunto_de_datos_enadid_2018_csv.zip
    + enadid18_tabulados_principales_resultados_xlsx.zip
    + fd_enadid18.xlsx
    + usa_00056.dta.gz

In [23]:
ZipFile(DATOS_BRUTOS / 'conjunto_de_datos_enadid_2018_csv.zip').extractall(DATOS_BRUTOS / 'enadid18/')

In [31]:
DATOS_MIGRANTE = Path(DATOS_BRUTOS / 'enadid18' / "conjunto_de_datos_tmigrante_enadid_2018")
arbol(DATOS_MIGRANTE)

+ ..\datos\brutos\enadid18\conjunto_de_datos_tmigrante_enadid_2018
    + catalogos
        + cond_resid.csv
        + doc_mig.csv
        + ent.csv
        + estrato.csv
        + p4_10_1.csv
        + p4_11.csv
        + p4_11c.csv
        + p4_12.csv
        + p4_12c.csv
        + p4_13.csv
        + p4_14.csv
        + p4_14a.csv
        + p4_14c.csv
        + P4_15.csv
        + p4_15c.csv
        + p4_16.csv
        + p4_16c.csv
        + p4_17.csv
        + p4_17ac.csv
        + p4_17bc.csv
        + p4_18_1.csv
        + p4_19.csv
        + p4_19c.csv
        + p4_20_1.csv
        + p4_4.csv
        + p4_5.csv
        + p4_5ac.csv
        + p4_5bc.csv
        + p4_6.csv
        + p4_7.csv
        + p4_7c.csv
        + p4_8_ag1.csv
        + p4_8_ag2.csv
        + p4_9.csv
        + p4_9c.csv
        + t_loc_ag1.csv
        + t_loc_ur.csv
        + tam_loc.csv
        + tpo_mig_ag.csv
    + conjunto_de_datos
        + conjunto_de_datos_tmigrante_enadid_2018.csv
    + diccionario_de_datos
        + diccionario_datos_tmigrante_enadid_2018.csv
    + metadatos
        + metadatos_enadid_2018.txt
    + modelo_entidad_relacion
        + modelo_er_enadid_2018.jpg
        + Thumbs.db

In [95]:
datos_migrante = pd.read_csv(DATOS_MIGRANTE / 'conjunto_de_datos/' / 'conjunto_de_datos_tmigrante_enadid_2018.csv')

In [96]:
datos_migrante.head().T

                      0            1            2            3            4
upm             2601551       762003       101193      1661789      1661789
viv_sel               2            4            5           14           19
hogar                 1            1            1            1            1
n_ren                 1            1            1            1            1
llave_mig   2.60155e+11  7.62003e+10  1.01193e+10  1.66179e+11  1.66179e+11
llave_per   2.60155e+11  7.62003e+10          NaN  1.66179e+11          NaN
llave_hog    2601551021    762003041    101193051   1661789141   1661789191
llave_viv     260155102     76200304     10119305    166178914    166178919
ent                  26            7            1           16           16
tam_loc               1            4            1            4            4
p4_4                  1            1            1            1            1
p4_5                  2            1            2            1            1
p4_5ac               14            7           14           16           16
p4_5bc              NaN          NaN          NaN          NaN          NaN
p4_6                  1            1            1            1            1
p4_7                  1            1            5            1            1
p4_7c               NaN          NaN          NaN          NaN          NaN
p4_8                 15           44           24           31           60
p4_9                  1            1            1            1            1
p4_9c               NaN          NaN          NaN          NaN          NaN
p4_10_1               8            5            1           11            7
p4_10_2            2013         2015         2015         2016         2018
p4_11                 1            1            1            1            1
p4_11c              221          221          221          221          221
p4_12                 7            2            2            7            5
p4_12c               37          NaN          NaN           41          NaN
p4_13                 4            6            7            7            2
p4_14                 2            1            1            1            1
p4_14a              NaN            b            b            a            b
p4_14c              NaN          NaN          NaN          NaN          NaN
p4_15                 2            2            1            2            1
p4_15c              NaN          NaN          221          NaN          221
p4_16               NaN          NaN            2          NaN            5
p4_16c              NaN          NaN            2          NaN            5
p4_17                 7            2          NaN            7          NaN
p4_17ac              37          NaN          NaN           41          NaN
p4_17bc             NaN          NaN          NaN          NaN          NaN
p4_18_1               5            6          NaN            4          NaN
p4_18_2            2017         2017          NaN         2018          NaN
p4_19                 2            3          NaN            4          NaN
p4_19c              NaN          NaN          NaN          NaN          NaN
p4_20_1               1            1          NaN            1          NaN
p4_20_2               1            1          NaN            1          NaN
fac_viv             288          408          121          329          329
t_loc_ur              1            2            1            2            2
t_loc_ag1             1            2            1            2            2
p4_8_ag1              4            9            5            7           13
p4_8_ag2              2            3            2            3            4
doc_mig               1            1            2            2            1
cond_resid            1            1            2            1            2
tpo_mig              45           25          NaN           17          NaN
tpo_mig_ag            3            2          NaN            2          NaN
estrato               4            1            2            1            1
est_dis             453          126            1          294          294
upm_dis           12170         3437          268         7715         7715

In [97]:
catalogos = DATOS_MIGRANTE.joinpath("catalogos").glob("*.csv")
# list(catalogos)

In [98]:
datos_catalogos = pd.DataFrame()
for catalogo in catalogos:
    working_df = pd.read_csv(catalogo, encoding = 'latin1')
    working_df['pregunta'] = catalogo.stem
    datos_catalogos = pd.concat((datos_catalogos, working_df), ignore_index = True)

In [99]:
datos_catalogos

    cve                                      descrip    pregunta
0     1                                      Retornó  cond_resid
1     2                                   No retornó  cond_resid
2     9                   NE condición de residencia  cond_resid
3     1                                Con documento     doc_mig
4     2                                Sin documento     doc_mig
5     9                                      No sabe     doc_mig
6     1                               Aguascalientes         ent
7     2                              Baja California         ent
8     3                          Baja California Sur         ent
9     4                                     Campeche         ent
10    5                         Coahuila de Zaragoza         ent
11    6                                       Colima         ent
12    7                                      Chiapas         ent
13    8                                    Chihuahua         ent
14    9                             Ciudad de México         ent
15   10                                      Durango         ent
16   11                                   Guanajuato         ent
17   12                                     Guerrero         ent
18   13                                      Hidalgo         ent
19   14                                      Jalisco         ent
20   15                             Estado de México         ent
21   16                          Michoacán de Ocampo         ent
22   17                                      Morelos         ent
23   18                                      Nayarit         ent
24   19                                   Nuevo León         ent
25   20                                       Oaxaca         ent
26   21                                       Puebla         ent
27   22                                    Querétaro         ent
28   23                                 Quintana Roo         ent
29   24                              San Luis Potosí         ent
..   ..                                          ...         ...
510  16                          Michoacán de Ocampo       p4_9c
511  17                                      Morelos       p4_9c
512  18                                      Nayarit       p4_9c
513  19                                   Nuevo León       p4_9c
514  20                                       Oaxaca       p4_9c
515  21                                       Puebla       p4_9c
516  22                                    Querétaro       p4_9c
517  23                                 Quintana Roo       p4_9c
518  24                              San Luis Potosí       p4_9c
519  25                                      Sinaloa       p4_9c
520  26                                       Sonora       p4_9c
521  27                                      Tabasco       p4_9c
522  28                                   Tamaulipas       p4_9c
523  29                                     Tlaxcala       p4_9c
524  30              Veracruz de Ignacio de la Llave       p4_9c
525  31                                      Yucatán       p4_9c
526  32                                    Zacatecas       p4_9c
527  99           Entidad federativa no especificada       p4_9c
528   1        Localidad de 100 000 y más habitantes     tam_loc
529   2      Localidad de 15 000 a 99 999 habitantes     tam_loc
530   3       Localidad de 2 500 a 14 999 habitantes     tam_loc
531   4          Localidad menor de 2 500 habitantes     tam_loc
532   1                              Menos de un año  tpo_mig_ag
533   2                           De un año a 3 años  tpo_mig_ag
534   3                                De 3 a 5 años  tpo_mig_ag
535   9                              No especificado  tpo_mig_ag
536   1         Localidad de 15 000 y más habitantes   t_loc_ag1
537   2         Localidad menor de 15 000 habitantes   t_loc_ag1
538   1    Localidad Urbana (2 500 y más habitantes)    t_loc_ur
539   2  Localidad Rural (menos de 2 500 habitantes)    t_loc_ur

[540 rows x 3 columns]

In [100]:
variables_dic = {}
for valor_pregunta in datos_catalogos['pregunta'].unique():
    working_df = datos_catalogos[datos_catalogos['pregunta'] == valor_pregunta]
    variables_dic[valor_pregunta] = {}
    for indice, valores in working_df[['cve', 'descrip']].iterrows():
        variables_dic[valor_pregunta][valores[0]] = valores[1]

In [101]:
variables_dic

{'cond_resid': {1: 'Retornó',
  2: 'No retornó',
  9: 'NE condición de residencia'},
 'doc_mig': {1: 'Con documento', 2: 'Sin documento', 9: 'No sabe'},
 'ent': {1: 'Aguascalientes',
  2: 'Baja California',
  3: 'Baja California Sur',
  4: 'Campeche',
  5: 'Coahuila de Zaragoza',
  6: 'Colima',
  7: 'Chiapas',
  8: 'Chihuahua',
  9: 'Ciudad de México',
  10: 'Durango',
  11: 'Guanajuato',
  12: 'Guerrero',
  13: 'Hidalgo',
  14: 'Jalisco',
  15: 'Estado de México',
  16: 'Michoacán de Ocampo',
  17: 'Morelos',
  18: 'Nayarit',
  19: 'Nuevo León',
  20: 'Oaxaca',
  21: 'Puebla',
  22: 'Querétaro',
  23: 'Quintana Roo',
  24: 'San Luis Potosí',
  25: 'Sinaloa',
  26: 'Sonora',
  27: 'Tabasco',
  28: 'Tamaulipas',
  29: 'Tlaxcala',
  30: 'Veracruz de Ignacio de la Llave',
  31: 'Yucatán',
  32: 'Zacatecas'},
 'estrato': {1: 'Bajo', 2: 'Medio bajo', 3: 'Medio alto', 4: 'Alto'},
 'p4_10_1': {1: 'Enero',
  2: 'Febrero',
  3: 'Marzo',
  4: 'Abril',
  5: 'Mayo',
  6: 'Junio',
  7: 'Julio',
  8: 'Agosto',
  9: 'Septiembre',
  10: 'Octubre',
  11: 'Noviembre',
  12: 'Diciembre',
  99: 'Fecha de emigración no especificada'},
 'p4_11': {1: 'Estados Unidos de América', 2: 'Otro país'},
 'p4_11c': {126: 'REPUBLICA DE KENIA',
  154: 'REPUBLICA DE SUDAFRICA',
  204: 'ARGENTINA',
  207: 'BARBADOS',
  208: 'BELICE',
  211: 'REPUBLICA FEDERATIVA DE BRASIL',
  213: 'CANADA',
  214: 'REPUBLICA DE COLOMBIA',
  215: 'REPUBLICA DE COSTA RICA',
  216: 'REPUBLICA DE CUBA',
  217: 'REPUBLICA DE CHILE',
  219: 'REPUBLICA DEL ECUADOR',
  220: 'REPUBLICA DE EL SALVADOR',
  221: 'ESTADOS UNIDOS DE AMERICA',
  225: 'REPUBLICA DE GUATEMALA',
  229: 'REPUBLICA DE HONDURAS',
  234: 'REPUBLICA DE NICARAGUA',
  235: 'REPUBLICA DE PANAMA',
  237: 'REPUBLICA DE PERU',
  239: 'REPUBLICA DOMINICANA',
  315: 'REPUBLICA POPULAR CHINA',
  321: 'EMIRATOS ARABES UNIDOS',
  329: 'ESTADO DE ISRAEL',
  330: 'ESTADO DE JAPON',
  332: 'REPUBLICA DE KAZAJSTAN',
  335: 'REPUBLICA LIBANESA',
  349: 'REINO DE TAILANDIA',
  400: 'EUROPA',
  402: 'REPUBLICA FEDERAL DE ALEMANIA',
  405: 'REPUBLICA DE AUSTRIA',
  408: 'REINO DE BELGICA',
  412: 'REINO DE DINAMARCA',
  415: 'REINO DE ESPAÑA',
  419: 'REPUBLICA FRANCESA',
  425: 'REPUBLICA ITALIANA',
  426: 'REPUBLICA DE LETONIA',
  436: 'REINO DE LOS PAISES BAJOS',
  438: 'REPUBLICA PORTUGUESA',
  439: 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA',
  441: 'RUMANIA',
  442: 'FEDERACION DE RUSIA',
  446: 'CONFEDERACION SUIZA',
  447: 'UCRANIA',
  501: 'COMMONWEALTH DE AUSTRALIA',
  520: 'NUEVA ZELANDA',
  600: 'PAIS NO ESPECIFICADO'},
 'p4_12': {1: 'California',
  2: 'Texas',
  3: 'Florida',
  4: 'Arizona',
  5: 'Nueva York',
  6: 'Illinois',
  7: 'Otro estado'},
 'p4_12c': {7: 'ALABAMA',
  8: 'ALASKA',
  9: 'ARKANSAS',
  10: 'CAROLINA DEL NORTE',
  11: 'CAROLINA DEL SUR',
  12: 'COLORADO',
  15: 'DAKOTA DEL SUR',
  16: 'DELAWARE',
  17: 'GEORGIA',
  18: 'HAWAII',
  19: 'IDAHO',
  20: 'INDIANA',
  21: 'IOWA',
  22: 'KANSAS',
  23: 'KENTUCKY',
  24: 'LOUISIANA',
  25: 'MAINE',
  26: 'MARYLAND',
  27: 'MASSACHUSETTS',
  28: 'MICHIGAN',
  29: 'MINNESOTA',
  30: 'MISSISSIPPI',
  31: 'MISSOURI',
  32: 'MONTANA',
  33: 'NEBRASKA',
  34: 'NEVADA',
  35: 'NEW HAMPSHIRE',
  36: 'NEW JERSEY',
  37: 'NUEVO MEXICO',
  38: 'OHIO',
  39: 'OKLAHOMA',
  40: 'OREGON',
  41: 'PENNSYLVANIA',
  42: 'RHODE ISLAND',
  43: 'TENNESSEE',
  44: 'UTAH',
  46: 'VIRGINIA',
  48: 'WASHINGTON',
  49: 'WISCONSIN',
  99: 'ESTADO DE EEUU NO ESPECIFICADO'},
 'p4_13': {1: 'Permiso para residir',
  2: 'Permiso para trabajar (green card)',
  3: 'Visa de turista',
  4: 'Visa de estudiante',
  5: 'Es ciudadano(a) estadounidense',
  6: 'Otro documento',
  7: 'Ningún documento',
  9: 'No sabe'},
 'p4_14': {1: 'Buscar trabajo o trabajar',
  2: 'Estudiar',
  3: 'Reunirse con la familia',
  4: 'Inseguridad pública o violencia',
  9: 'Otro motivo'},
 'p4_14a': {'A': '¿Se fue a buscar trabajo?', 'B': '¿Se fue con trabajo?'},
 'p4_14c': {6: 'RegularizaciÃ³n migratoria', 9: 'No sabe'},
 'P4_15': {1: 'Estados Unidos de América',
  2: 'México',
  3: 'Otro país',
  9: 'País de residencia actual no especificado'},
 'p4_15c': {204: 'ARGENTINA',
  211: 'REPUBLICA FEDERATIVA DE BRASIL',
  213: 'CANADA',
  214: 'REPUBLICA DE COLOMBIA',
  215: 'REPUBLICA DE COSTA RICA',
  219: 'REPUBLICA DEL ECUADOR',
  221: 'ESTADOS UNIDOS DE AMERICA',
  225: 'REPUBLICA DE GUATEMALA',
  229: 'REPUBLICA DE HONDURAS',
  234: 'REPUBLICA DE NICARAGUA',
  235: 'REPUBLICA DE PANAMA',
  237: 'REPUBLICA DE PERU',
  315: 'REPUBLICA POPULAR CHINA',
  321: 'EMIRATOS ARABES UNIDOS',
  329: 'ESTADO DE ISRAEL',
  332: 'REPUBLICA DE KAZAJSTAN',
  349: 'REINO DE TAILANDIA',
  400: 'EUROPA',
  402: 'REPUBLICA FEDERAL DE ALEMANIA',
  403: 'PRINCIPADO DE ANDORRA',
  408: 'REINO DE BELGICA',
  412: 'REINO DE DINAMARCA',
  415: 'REINO DE ESPAÑA',
  419: 'REPUBLICA FRANCESA',
  425: 'REPUBLICA ITALIANA',
  426: 'REPUBLICA DE LETONIA',
  439: 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA',
  446: 'CONFEDERACION SUIZA',
  501: 'COMMONWEALTH DE AUSTRALIA',
  520: 'NUEVA ZELANDA',
  600: 'PAIS NO ESPECIFICADO'},
 'p4_16': {1: 'California',
  2: 'Texas',
  3: 'Florida',
  4: 'Arizona',
  5: 'Nueva York',
  6: 'Illinois',
  7: 'Otro estado'},
 'p4_16c': {1: 'CALIFORNIA',
  2: 'TEXAS',
  3: 'ILLINOIS',
  4: 'ARIZONA',
  5: 'NUEVA YORK',
  6: 'FLORIDA',
  7: 'ALABAMA',
  8: 'ALASKA',
  9: 'ARKANSAS',
  10: 'CAROLINA DEL NORTE',
  11: 'CAROLINA DEL SUR',
  12: 'COLORADO',
  14: 'DAKOTA DEL NORTE',
  15: 'DAKOTA DEL SUR',
  16: 'DELAWARE',
  17: 'GEORGIA',
  18: 'HAWAII',
  19: 'IDAHO',
  20: 'INDIANA',
  21: 'IOWA',
  22: 'KANSAS',
  23: 'KENTUCKY',
  24: 'LOUISIANA',
  26: 'MARYLAND',
  27: 'MASSACHUSETTS',
  28: 'MICHIGAN',
  29: 'MINNESOTA',
  30: 'MISSISSIPPI',
  31: 'MISSOURI',
  32: 'MONTANA',
  33: 'NEBRASKA',
  34: 'NEVADA',
  35: 'NEW HAMPSHIRE',
  36: 'NEW JERSEY',
  37: 'NUEVO MEXICO',
  38: 'OHIO',
  39: 'OKLAHOMA',
  40: 'OREGON',
  41: 'PENNSYLVANIA',
  43: 'TENNESSEE',
  44: 'UTAH',
  46: 'VIRGINIA',
  48: 'WASHINGTON',
  49: 'WISCONSIN',
  99: 'ESTADO DE EEUU NO ESPECIFICADO'},
 'p4_17': {1: 'California',
  2: 'Texas',
  3: 'Florida',
  4: 'Arizona',
  7: 'Otro estado',
  8: 'Otro país'},
 'p4_17ac': {5: 'NUEVA YORK',
  6: 'FLORIDA',
  7: 'ALABAMA',
  8: 'ALASKA',
  9: 'ARKANSAS',
  10: 'CAROLINA DEL NORTE',
  11: 'CAROLINA DEL SUR',
  12: 'COLORADO',
  14: 'DAKOTA DEL NORTE',
  16: 'DELAWARE',
  17: 'GEORGIA',
  19: 'IDAHO',
  20: 'INDIANA',
  21: 'IOWA',
  22: 'KANSAS',
  23: 'KENTUCKY',
  24: 'LOUISIANA',
  25: 'MAINE',
  26: 'MARYLAND',
  27: 'MASSACHUSETTS',
  28: 'MICHIGAN',
  29: 'MINNESOTA',
  30: 'MISSISSIPPI',
  31: 'MISSOURI',
  33: 'NEBRASKA',
  34: 'NEVADA',
  35: 'NEW HAMPSHIRE',
  36: 'NEW JERSEY',
  37: 'NUEVO MEXICO',
  38: 'OHIO',
  39: 'OKLAHOMA',
  40: 'OREGON',
  41: 'PENNSYLVANIA',
  42: 'RHODE ISLAND',
  43: 'TENNESSEE',
  44: 'UTAH',
  46: 'VIRGINIA',
  48: 'WASHINGTON',
  49: 'WISCONSIN',
  99: 'ESTADO DE EEUU NO ESPECIFICADO'},
 'p4_17bc': {126: 'REPUBLICA DE KENIA',
  135: 'REINO DE MARRUECOS',
  142: 'REPUBLICA FEDERAL DE NIGERIA',
  154: 'REPUBLICA DE SUDAFRICA',
  201: 'ANGUILA',
  204: 'ARGENTINA',
  207: 'BARBADOS',
  208: 'BELICE',
  210: 'REPUBLICA DE BOLIVIA',
  211: 'REPUBLICA FEDERATIVA DE BRASIL',
  213: 'CANADA',
  214: 'REPUBLICA DE COLOMBIA',
  215: 'REPUBLICA DE COSTA RICA',
  216: 'REPUBLICA DE CUBA',
  217: 'REPUBLICA DE CHILE',
  219: 'REPUBLICA DEL ECUADOR',
  220: 'REPUBLICA DE EL SALVADOR',
  221: 'ESTADOS UNIDOS DE AMERICA',
  225: 'REPUBLICA DE GUATEMALA',
  228: 'REPUBLICA DE HAITI',
  229: 'REPUBLICA DE HONDURAS',
  230: 'JAMAICA',
  234: 'REPUBLICA DE NICARAGUA',
  235: 'REPUBLICA DE PANAMA',
  236: 'REPUBLICA DE PARAGUAY',
  237: 'REPUBLICA DE PERU',
  238: 'ESTADO LIBRE ASOCIADO DE PUERTO RICO',
  239: 'REPUBLICA DOMINICANA',
  247: 'REPUBLICA ORIENTAL DEL URUGUAY',
  250: 'REPUBLICA BOLIVARIANA DE VENEZUELA',
  300: 'ASIA',
  313: 'REPUBLICA DE COREA',
  315: 'REPUBLICA POPULAR CHINA',
  321: 'EMIRATOS ARABES UNIDOS',
  322: 'REPUBLICA DE FILIPINAS',
  325: 'REPUBLICA DE LA INDIA',
  327: 'REPUBLICA ISLAMICA DE IRAN',
  329: 'ESTADO DE ISRAEL',
  330: 'ESTADO DE JAPON',
  332: 'REPUBLICA DE KAZAJSTAN',
  335: 'REPUBLICA LIBANESA',
  349: 'REINO DE TAILANDIA',
  352: 'REPUBLICA DE TURQUIA',
  400: 'EUROPA',
  402: 'REPUBLICA FEDERAL DE ALEMANIA',
  403: 'PRINCIPADO DE ANDORRA',
  405: 'REPUBLICA DE AUSTRIA',
  407: 'REPUBLICA DE BIELORRUSIA',
  408: 'REINO DE BELGICA',
  412: 'REINO DE DINAMARCA',
  415: 'REINO DE ESPAÑA',
  419: 'REPUBLICA FRANCESA',
  421: 'REPUBLICA HELENICA',
  422: 'REPUBLICA DE HUNGRIA',
  423: 'REPUBLICA DE IRLANDA',
  425: 'REPUBLICA ITALIANA',
  426: 'REPUBLICA DE LETONIA',
  436: 'REINO DE LOS PAISES BAJOS',
  437: 'REPUBLICA DE POLONIA',
  438: 'REPUBLICA PORTUGUESA',
  439: 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA',
  440: 'REPUBLICA CHECA',
  441: 'RUMANIA',
  442: 'FEDERACION DE RUSIA',
  446: 'CONFEDERACION SUIZA',
  447: 'UCRANIA',
  501: 'COMMONWEALTH DE AUSTRALIA',
  520: 'NUEVA ZELANDA',
  600: 'PAIS NO ESPECIFICADO'},
 'p4_18_1': {1: 'Enero',
  2: 'Febrero',
  3: 'Marzo',
  4: 'Abril',
  5: 'Mayo',
  6: 'Junio',
  7: 'Julio',
  8: 'Agosto',
  9: 'Septiembre',
  10: 'Octubre',
  11: 'Noviembre',
  12: 'Diciembre',
  99: 'No sabe'},
 'p4_19': {1: 'Falta de trabajo',
  2: 'Terminó estudios',
  3: 'Reunirse con la familia',
  4: 'Le deportaron (regresaron)',
  5: 'Otro motivo'},
 'p4_19c': {5: 'Otro motivo',
  6: 'Estudiar o trabajar en México',
  7: 'Vencimiento de autorización migratoria'},
 'p4_20_1': {1: 'Sí', 2: 'No'},
 'p4_4': {1: 'Sí', 2: 'No'},
 'p4_5': {1: 'Aquí, en este estado',
  2: 'En otro estado',
  3: 'En Estados Unidos de América',
  4: 'En otro país'},
 'p4_5ac': {1: 'Aguascalientes',
  2: 'Baja California',
  3: 'Baja California Sur',
  4: 'Campeche',
  5: 'Coahuila de Zaragoza',
  6: 'Colima',
  7: 'Chiapas',
  8: 'Chihuahua',
  9: 'Ciudad de México',
  10: 'Durango',
  11: 'Guanajuato',
  12: 'Guerrero',
  13: 'Hidalgo',
  14: 'Jalisco',
  15: 'Estado de México',
  16: 'Michoacán de Ocampo',
  17: 'Morelos',
  18: 'Nayarit',
  19: 'Nuevo León',
  20: 'Oaxaca',
  21: 'Puebla',
  22: 'Querétaro',
  23: 'Quintana Roo',
  24: 'San Luis Potosí',
  25: 'Sinaloa',
  26: 'Sonora',
  27: 'Tabasco',
  28: 'Tamaulipas',
  29: 'Tlaxcala',
  30: 'Veracruz de Ignacio de la Llave',
  31: 'Yucatán',
  32: 'Zacatecas',
  99: 'Entidad federativa no especificada'},
 'p4_5bc': {126: 'REPUBLICA DE KENIA',
  208: 'BELICE',
  213: 'CANADA',
  215: 'REPUBLICA DE COSTA RICA',
  216: 'REPUBLICA DE CUBA',
  225: 'REPUBLICA DE GUATEMALA',
  229: 'REPUBLICA DE HONDURAS',
  238: 'ESTADO LIBRE ASOCIADO DE PUERTO RICO',
  402: 'REPUBLICA FEDERAL DE ALEMANIA',
  415: 'REINO DE ESPAÑA',
  419: 'REPUBLICA FRANCESA',
  426: 'REPUBLICA DE LETONIA',
  439: 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA',
  446: 'CONFEDERACION SUIZA',
  501: 'COMMONWEALTH DE AUSTRALIA',
  600: 'PAIS NO ESPECIFICADO'},
 'p4_6': {1: 'Hombre', 2: 'Mujer'},
 'p4_7': {1: 'Jefa(e)',
  2: 'Esposa(o) o compañera(o)',
  3: 'Hija(o)',
  4: 'Nieta(o)',
  5: 'Nuera/yerno',
  8: 'Otro'},
 'p4_7c': {303: 'Hijastra o hijastro',
  401: 'Madre o padre',
  402: 'Madrastra o padrastro',
  403: 'Hermana o hermano',
  405: 'Hermanastra o hermanastro',
  406: 'Abuela o abuelo',
  412: 'Tía o tío',
  413: 'Sobrina o sobrino',
  414: 'Prima o primo',
  415: 'Suegra o suegro',
  418: 'Cuñada o cuñado',
  423: 'Otro parentesco',
  501: 'Sin parentesco',
  999: 'Parentesco no especificado'},
 'p4_8_ag1': {1: '00 a 05 años',
  2: '05 a 09 años',
  3: '10 a 14 años',
  4: '15 a 19 años',
  5: '20 a 24 años',
  6: '25 a 29 años',
  7: '30 a 34 años',
  8: '35 a 39 años',
  9: '40 a 44 años',
  10: '45 a 49 años',
  11: '50 a 54 años',
  12: '55 a 59 años',
  13: '60 a 64 años',
  14: '65 a 69 años',
  15: '70 a 74 años',
  16: '75 a 79 años',
  17: '80 a 84 años',
  18: '85 y más años',
  19: 'Edad no especificada'},
 'p4_8_ag2': {1: '00 a 17 años',
  2: '18 a 29 años',
  3: '30 a 59 años',
  4: '60 y más años',
  9: 'NE Edad al emigrar'},
 'p4_9': {1: 'Aquí, en este estado', 2: 'En otro estado'},
 'p4_9c': {1: 'Aguascalientes',
  2: 'Baja California',
  3: 'Baja California Sur',
  4: 'Campeche',
  5: 'Coahuila de Zaragoza',
  6: 'Colima',
  7: 'Chiapas',
  8: 'Chihuahua',
  9: 'Ciudad de México',
  10: 'Durango',
  11: 'Guanajuato',
  12: 'Guerrero',
  13: 'Hidalgo',
  14: 'Jalisco',
  15: 'Estado de México',
  16: 'Michoacán de Ocampo',
  17: 'Morelos',
  18: 'Nayarit',
  19: 'Nuevo León',
  20: 'Oaxaca',
  21: 'Puebla',
  22: 'Querétaro',
  23: 'Quintana Roo',
  24: 'San Luis Potosí',
  25: 'Sinaloa',
  26: 'Sonora',
  27: 'Tabasco',
  28: 'Tamaulipas',
  29: 'Tlaxcala',
  30: 'Veracruz de Ignacio de la Llave',
  31: 'Yucatán',
  32: 'Zacatecas',
  99: 'Entidad federativa no especificada'},
 'tam_loc': {1: 'Localidad de 100 000 y más habitantes',
  2: 'Localidad de 15 000 a 99 999 habitantes',
  3: 'Localidad de 2 500 a 14 999 habitantes',
  4: 'Localidad menor de 2 500 habitantes'},
 'tpo_mig_ag': {1: 'Menos de un año',
  2: 'De un año a 3 años',
  3: 'De 3 a 5 años',
  9: 'No especificado'},
 't_loc_ag1': {1: 'Localidad de 15 000 y más habitantes',
  2: 'Localidad menor de 15 000 habitantes'},
 't_loc_ur': {1: 'Localidad Urbana (2 500 y más habitantes)',
  2: 'Localidad Rural (menos de 2 500 habitantes)'}}

In [102]:
variables_dic.keys()

dict_keys(['cond_resid', 'doc_mig', 'ent', 'estrato', 'p4_10_1', 'p4_11', 'p4_11c', 'p4_12', 'p4_12c', 'p4_13', 'p4_14', 'p4_14a', 'p4_14c', 'P4_15', 'p4_15c', 'p4_16', 'p4_16c', 'p4_17', 'p4_17ac', 'p4_17bc', 'p4_18_1', 'p4_19', 'p4_19c', 'p4_20_1', 'p4_4', 'p4_5', 'p4_5ac', 'p4_5bc', 'p4_6', 'p4_7', 'p4_7c', 'p4_8_ag1', 'p4_8_ag2', 'p4_9', 'p4_9c', 'tam_loc', 'tpo_mig_ag', 't_loc_ag1', 't_loc_ur'])

In [103]:
datos_migrante.columns

Index(['upm', 'viv_sel', 'hogar', 'n_ren', 'llave_mig', 'llave_per',
       'llave_hog', 'llave_viv', 'ent', 'tam_loc', 'p4_4', 'p4_5', 'p4_5ac',
       'p4_5bc', 'p4_6', 'p4_7', 'p4_7c', 'p4_8', 'p4_9', 'p4_9c', 'p4_10_1',
       'p4_10_2', 'p4_11', 'p4_11c', 'p4_12', 'p4_12c', 'p4_13', 'p4_14',
       'p4_14a', 'p4_14c', 'p4_15', 'p4_15c', 'p4_16', 'p4_16c', 'p4_17',
       'p4_17ac', 'p4_17bc', 'p4_18_1', 'p4_18_2', 'p4_19', 'p4_19c',
       'p4_20_1', 'p4_20_2', 'fac_viv', 't_loc_ur', 't_loc_ag1', 'p4_8_ag1',
       'p4_8_ag2', 'doc_mig', 'cond_resid', 'tpo_mig', 'tpo_mig_ag', 'estrato',
       'est_dis', 'upm_dis'],
      dtype='object')

In [104]:
for key in variables_dic.keys():
    if key in datos_migrante.columns:
        datos_migrante[key] = datos_migrante[key].map(variables_dic[key])
    else:
        pass

In [106]:
datos_migrante.head().T

,0,1,2,3,4
upm,2601551,762003,101193,1661789,1661789
viv_sel,2,4,5,14,19
hogar,1,1,1,1,1
n_ren,1,1,1,1,1
llave_mig,2.60155e+11,7.62003e+10,1.01193e+10,1.66179e+11,1.66179e+11
llave_per,2.60155e+11,7.62003e+10,NaN,1.66179e+11,NaN
llave_hog,2601551021,762003041,101193051,1661789141,1661789191
llave_viv,260155102,76200304,10119305,166178914,166178919
ent,Sonora,Chiapas,Aguascalientes,Michoacán de Ocampo,Michoacán de Ocampo
tam_loc,Localidad de 100 000 y más habitantes,Localidad menor de 2 500 habitantes,Localidad de 100 000 y más habitantes,Localidad menor de 2 500 habitantes,Localidad menor de 2 500 habitantes
p4_4,Sí,Sí,Sí,Sí,Sí
p4_5,En otro estado,"Aquí, en este estado",En otro estado,"Aquí, en este estado","Aquí, en este estado"
p4_5ac,Jalisco,Chiapas,Jalisco,Michoacán de Ocampo,Michoacán de Ocampo
p4_5bc,NaN,NaN,NaN,NaN,NaN
p4_6,Hombre,Hombre,Hombre,Hombre,Hombre
p4_7,Jefa(e),Jefa(e),Nuera/yerno,Jefa(e),Jefa(e)
p4_7c,NaN,NaN,NaN,NaN,NaN
p4_8,15,44,24,31,60
p4_9,"Aquí, en este estado","Aquí, en este estado","Aquí, en este estado","Aquí, en este estado","Aquí, en este estado"
p4_9c,NaN,NaN,NaN,NaN,NaN
p4_10_1,Agosto,Mayo,Enero,Noviembre,Julio
p4_10_2,2013,2015,2015,2016,2018
p4_11,Estados Unidos de América,Estados Unidos de América,Estados Unidos de América,Estados Unidos de América,Estados Unidos de América
p4_11c,ESTADOS UNIDOS DE AMERICA,ESTADOS UNIDOS DE AMERICA,ESTADOS UNIDOS DE AMERICA,ESTADOS UNIDOS DE AMERICA,ESTADOS UNIDOS DE AMERICA
p4_12,Otro estado,Texas,Texas,Otro estado,Nueva York
p4_12c,NUEVO MEXICO,NaN,NaN,PENNSYLVANIA,NaN
p4_13,Visa de estudiante,Otro documento,Ningún documento,Ningún documento,Permiso para trabajar (green card)
p4_14,Estudiar,Buscar trabajo o trabajar,Buscar trabajo o trabajar,Buscar trabajo o trabajar,Buscar trabajo o trabajar
p4_14a,NaN,NaN,NaN,NaN,NaN
p4_14c,NaN,NaN,NaN,NaN,NaN
p4_15,2,2,1,2,1
p4_15c,NaN,NaN,ESTADOS UNIDOS DE AMERICA,NaN,ESTADOS UNIDOS DE AMERICA
p4_16,NaN,NaN,Texas,NaN,Nueva York
p4_16c,NaN,NaN,TEXAS,NaN,NUEVA YORK
p4_17,Otro estado,Texas,NaN,Otro estado,NaN
p4_17ac,NUEVO MEXICO,NaN,NaN,PENNSYLVANIA,NaN
p4_17bc,NaN,NaN,NaN,NaN,NaN
p4_18_1,Mayo,Junio,NaN,Abril,NaN
p4_18_2,2017,2017,NaN,2018,NaN
p4_19,Terminó estudios,Reunirse con la familia,NaN,Le deportaron (regresaron),NaN
p4_19c,NaN,NaN,NaN,NaN,NaN
p4_20_1,Sí,Sí,NaN,Sí,NaN
p4_20_2,1,1,NaN,1,NaN
fac_viv,288,408,121,329,329
t_loc_ur,Localidad Urbana (2 500 y más habitantes),Localidad Rural (menos de 2 500 habitantes),Localidad Urbana (2 500 y más habitantes),Localidad Rural (menos de 2 500 habitantes),Localidad Rural (menos de 2 500 habitantes)
t_loc_ag1,Localidad de 15 000 y más habitantes,Localidad menor de 15 000 habitantes,Localidad de 15 000 y más habitantes,Localidad menor de 15 000 habitantes,Localidad menor de 15 000 habitantes
p4_8_ag1,15 a 19 años,40 a 44 años,20 a 24 años,30 a 34 años,60 a 64 años
p4_8_ag2,18 a 29 años,30 a 59 años,18 a 29 años,30 a 59 años,60 y más años
doc_mig,Con documento,Con documento,Sin documento,Sin documento,Con documento
cond_resid,Retornó,Retornó,No retornó,Retornó,No retornó
tpo_mig,45,25,NaN,17,NaN
tpo_mig_ag,De 3 a 5 años,De un año a 3 años,NaN,De un año a 3 años,NaN
estrato,Alto,Bajo,Medio bajo,Bajo,Bajo
est_dis,453,126,1,294,294
upm_dis,12170,3437,268,7715,7715

In [71]:
arbol(DATOS_MIGRANTE)

+ ..\datos\brutos\enadid18\conjunto_de_datos_tmigrante_enadid_2018
    + catalogos
        + cond_resid.csv
        + doc_mig.csv
        + ent.csv
        + estrato.csv
        + p4_10_1.csv
        + p4_11.csv
        + p4_11c.csv
        + p4_12.csv
        + p4_12c.csv
        + p4_13.csv
        + p4_14.csv
        + p4_14a.csv
        + p4_14c.csv
        + P4_15.csv
        + p4_15c.csv
        + p4_16.csv
        + p4_16c.csv
        + p4_17.csv
        + p4_17ac.csv
        + p4_17bc.csv
        + p4_18_1.csv
        + p4_19.csv
        + p4_19c.csv
        + p4_20_1.csv
        + p4_4.csv
        + p4_5.csv
        + p4_5ac.csv
        + p4_5bc.csv
        + p4_6.csv
        + p4_7.csv
        + p4_7c.csv
        + p4_8_ag1.csv
        + p4_8_ag2.csv
        + p4_9.csv
        + p4_9c.csv
        + t_loc_ag1.csv
        + t_loc_ur.csv
        + tam_loc.csv
        + tpo_mig_ag.csv
    + conjunto_de_datos
        + conjunto_de_datos_tmigrante_enadid_2018.csv
    + diccionario_de_datos
        + diccionario_datos_tmigrante_enadid_2018.csv
    + metadatos
        + metadatos_enadid_2018.txt
    + modelo_entidad_relacion
        + modelo_er_enadid_2018.jpg
        + Thumbs.db

In [107]:
diccionario_datos = pd.read_csv(DATOS_MIGRANTE / 'diccionario_de_datos' / 'diccionario_datos_tmigrante_enadid_2018.csv', encoding = 'latin1')

In [108]:
diccionario_datos.head(15)

,nombre_campo,longitud,tipo,nemónico,catálogo,rango_claves
0,Unidad Primaria de Muestreo,7,C,UPM,NaN,0100001-3260039
1,Vivienda seleccionada,2,C,VIV_SEL,NaN,[01-10]
2,Consecutivo del hogar en la vivienda,1,C,HOGAR,NaN,[1-5]
3,Consecutivo del residente habitual miembro del...,2,C,N_REN,NaN,[01-25]
4,Clave Llave única para cada migrante internaci...,12,C,LLAVE_PER,NaN,010000101101-326003924725
5,Clave única de identificación del hogar (UPM+V...,10,C,LLAVE_HOG,NaN,0100001011-3260039247
6,Clave única de identificación de la vivienda (...,9,C,LLAVE_VIV,NaN,010000101-326003924
7,Clave de Entidad Federativa de levantamiento d...,2,C,ENT,ENT,[01-32]
8,Clave de tamaño de localidad,1,C,TAM_LOC,TAM_LOC,[1-4]
9,"P4.4 Cuando (NOMBRE) se fue la última vez, ¿vi...",1,C,P4_4,P4_4,"1,2"
10,P4.5 ¿En qué estado de la República Mexicana o...,1,C,P4_5,P4_5,[1-4]
11,P4.5 ¿En qué estado de la República Mexicana o...,2,C,P4_5AC,P4_5AC,"01-32,99"
12,P4.5 ¿En qué estado de la República Mexicana o...,3,C,P4_5BC,P4_5BC,100-501
13,P4.6 (NOMBRE) es hombre o mujer,1,C,P4_6,P4_6,"1,2"
14,P4.7 ¿Qué es (NOMBRE) de la jefa o jefe del ho...,1,C,P4_7,P4_7,"1-5,8"

In [109]:
columnas_dic = {}
for indice, valores in diccionario_datos[['nombre_campo', 'nemónico']].iterrows():
    columnas_dic[valores[1]] = valores[0]

In [110]:
columnas_dic

{'UPM': 'Unidad Primaria de Muestreo',
 'VIV_SEL': 'Vivienda seleccionada',
 'HOGAR': 'Consecutivo del hogar en la vivienda',
 'N_REN': 'Consecutivo del residente habitual miembro del hogar',
 'LLAVE_PER': 'Clave Llave única para cada migrante internacional delcalrado en el hogar en la base (UPM+VIV_SEL+HOGAR+N_REN)',
 'LLAVE_HOG': 'Clave única de identificación del hogar (UPM+VIV_SEL+ HOGAR)',
 'LLAVE_VIV': 'Clave única de identificación de la vivienda (UPM+VIV_SEL+HOGAR)',
 'ENT': 'Clave de Entidad Federativa de levantamiento de la información',
 'TAM_LOC': 'Clave de tamaño de localidad',
 'P4_4': 'P4.4 Cuando (NOMBRE) se fue la última vez, ¿vivía con ustedes?',
 'P4_5': 'P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?',
 'P4_5AC': 'P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otra entidad)',
 'P4_5BC': 'P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otro país)',
 'P4_6': 'P4.6 (NOMBRE) es hombre o mujer',
 'P4_7': 'P4.7 ¿Qué es (NOMBRE) de la jefa o jefe del hogar?',
 'P4_7C': 'P4.7 ¿Qué es (NOMBRE) de la jefa o jefe del hogar? (Otro parentesco)',
 'P4_8': 'P4.8 La última vez que (NOMBRE) se fue, ¿cuántos años cumplidos tenía?',
 'P4_9': 'P4.9 La última vez que (NOMBRE) se fue a vivir a otro país, ¿en qué estado de la República Mexicana vivía?',
 'P4_9C': 'P4.9 La última vez que (NOMBRE) se fue a vivir a otro país, ¿en qué estado de la República Mexicana vivía? (Otra entidad)',
 'P4_10_1': 'P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Mes)',
 'P4_10_2': 'P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año)',
 'P4_11': 'P4.11 ¿A qué país se fue (NOMBRE) la última vez?',
 'P4_11C': 'P4.11 ¿A qué país se fue (NOMBRE) la última vez? (Otro país)',
 'P4_12': 'P4.12 ¿A qué estado de EUA llegó (NOMBRE) a vivir (la última vez)?',
 'P4_12C': 'P4.12C ¿A qué estado de EUA llegó (NOMBRE) a vivir (la última vez)? (Otro estado)',
 'P4_13': 'P4.13 Cuando (NOMBRE) se fue la última vez, ¿qué tipo de documento llevaba?',
 'P4_14': 'P4.14 ¿Cuál fue el motivo principal por el que (NOMBRE) se fue la última vez?',
 'P4_14A': 'P4.14A ¿Se fue a buscar trabajo? ¿Con trabajo?',
 'p4_14C': 'P4.14 ¿Cuál fue el motivo principal por el que (NOMBRE) se fue la última vez? (Otro motivo)',
 'P4_15': 'P4.15 ¿En qué país vive actualmente (NOMBRE)?',
 'P4_15C': 'P4.15 ¿En qué país vive actualmente (NOMBRE)? (Otro país)',
 'P4_16': 'P4.16 ¿En qué estado de EUA vive actualmente (NOMBRE)?',
 'p4_16C': 'p4.16 ¿En qué estado de EUA vive actualmente (NOMBRE)? (Otro estado)',
 'P4_17': 'P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía?',
 'P4_17AC': 'P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía? (Otro estado)',
 'P4_17BC': 'P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía? (Otro país)',
 'P4_18_1': 'P4.18 ¿En qué mes y año regresó (NOMBRE) a vivir a la República Mexicana? (Mes)',
 'P4_18_2': 'P4.18 ¿En qué mes y año regresó (NOMBRE) a vivir a la República Mexicana? (Año)',
 'P4_19': 'P4.19 ¿Cuál fue el motivo principal por el que (NOMBRE) se regresó?',
 'P4_19C': 'P4.19 ¿Cuál fue el motivo principal por el que (NOMBRE) se regresó? (Otro motivo)',
 'P4_20_1': 'P4.20 (NOMBRE) actualmente forma parte de este hogar?',
 'P4_20_2': 'P4.20 Número de renglón en la lista de personas',
 'FAC_VIV': 'Factor de expansión a nivel vivienda',
 'T_LOC_UR': 'Tamaño de localidad, segunda agrupación',
 'T_LOC_AG1': 'Tamaño de localidad, tercera agrupación',
 'P4_8_AG1': 'P4.8.AG1 Edad al emigrar ( grupos quinquenales)',
 'P4_8_AG2': 'P4.8.AG2 Edad al emigrar por grandes grupos',
 'DOC_MIG': 'Condición de tenencia de documento para ingresar a EUA',
 'COND_RESID': 'Condición de retorno a México',
 'TPO_MIG': 'Duración de migración (en meses)',
 'TPO_MIG_AG': 'Duración de migración (agrupado)',
 'ESTRATO': 'Estrato sociodemográfico',
 'EST_DIS': 'Estrato de diseño muestral',
 'UPM_DIS': 'Unidad Primaria de Muestreo'}

In [111]:
datos_migrante.columns = datos_migrante.columns.str.upper().map(columnas_dic)

In [112]:
datos_migrante.columns

Index([                                                                                              'Unidad Primaria de Muestreo',
                                                                                                           'Vivienda seleccionada',
                                                                                            'Consecutivo del hogar en la vivienda',
                                                                            'Consecutivo del residente habitual miembro del hogar',
                                                                                                                               nan,
                  'Clave Llave única para cada migrante internacional delcalrado en el hogar en la base (UPM+VIV_SEL+HOGAR+N_REN)',
                                                                    'Clave única de identificación del hogar (UPM+VIV_SEL+ HOGAR)',
                                                                'Clave única de identificación de la vivienda (UPM+VIV_SEL+HOGAR)',
                                                                  'Clave de Entidad Federativa de levantamiento de la información',
                                                                                                    'Clave de tamaño de localidad',
                                                                  'P4.4 Cuando (NOMBRE) se fue la última vez, ¿vivía con ustedes?',
                                                             'P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?',
                                             'P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otra entidad)',
                                                'P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otro país)',
                                                                                                 'P4.6 (NOMBRE) es hombre o mujer',
                                                                              'P4.7 ¿Qué es (NOMBRE) de la jefa o jefe del hogar?',
                                                            'P4.7 ¿Qué es (NOMBRE) de la jefa o jefe del hogar? (Otro parentesco)',
                                                          'P4.8 La última vez que (NOMBRE) se fue, ¿cuántos años cumplidos tenía?',
                      'P4.9 La última vez que (NOMBRE) se fue a vivir a otro país, ¿en qué estado de la República Mexicana vivía?',
       'P4.9 La última vez que (NOMBRE) se fue a vivir a otro país, ¿en qué estado de la República Mexicana vivía? (Otra entidad)',
                                                'P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Mes)',
                                                'P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año)',
                                                                                'P4.11 ¿A qué país se fue (NOMBRE) la última vez?',
                                                                    'P4.11 ¿A qué país se fue (NOMBRE) la última vez? (Otro país)',
                                                              'P4.12 ¿A qué estado de EUA llegó (NOMBRE) a vivir (la última vez)?',
                                               'P4.12C ¿A qué estado de EUA llegó (NOMBRE) a vivir (la última vez)? (Otro estado)',
                                                     'P4.13 Cuando (NOMBRE) se fue la última vez, ¿qué tipo de documento llevaba?',
                                                   'P4.14 ¿Cuál fue el motivo principal por el que (NOMBRE) se fue la última vez?',
                                                                                  'P4.14A ¿Se fue a buscar trabajo? ¿Con trabajo?',
                                                                                                                               nan,
                                                                                   'P4.15 ¿En qué país vive actualmente (NOMBRE)?',
                                                                       'P4.15 ¿En qué país vive actualmente (NOMBRE)? (Otro país)',
                                                                          'P4.16 ¿En qué estado de EUA vive actualmente (NOMBRE)?',
                                                                                                                               nan,
                                                  'P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía?',
                                    'P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía? (Otro estado)',
                                      'P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía? (Otro país)',
                                                 'P4.18 ¿En qué mes y año regresó (NOMBRE) a vivir a la República Mexicana? (Mes)',
                                                 'P4.18 ¿En qué mes y año regresó (NOMBRE) a vivir a la República Mexicana? (Año)',
                                                             'P4.19 ¿Cuál fue el motivo principal por el que (NOMBRE) se regresó?',
                                               'P4.19 ¿Cuál fue el motivo principal por el que (NOMBRE) se regresó? (Otro motivo)',
                                                                           'P4.20 (NOMBRE) actualmente forma parte de este hogar?',
                                                                                 'P4.20 Número de renglón en la lista de personas',
                                                                                            'Factor de expansión a nivel vivienda',
                                                                                         'Tamaño de localidad, segunda agrupación',
                                                                                         'Tamaño de localidad, tercera agrupación',
                                                                                 'P4.8.AG1 Edad al emigrar ( grupos quinquenales)',
                                                                                     'P4.8.AG2 Edad al emigrar por grandes grupos',
                                                                          'Condición de tenencia de documento para ingresar a EUA',
                                                                                                   'Condición de retorno a México',
                                                                                                'Duración de migración (en meses)',
                                                                                                'Duración de migración (agrupado)',
                                                                                                        'Estrato sociodemográfico',
                                                                                                      'Estrato de diseño muestral',
                                                                                                     'Unidad Primaria de Muestreo'],
      dtype='object')

# Checkpoint

In [113]:
datos_migrante.to_csv(DATOS_PROCESADOS / 'datos_migrante.csv', index = False, encoding = 'utf-8')

***

In [114]:
datos_migrante.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2611 entries, 0 to 2610
Data columns (total 55 columns):
Unidad Primaria de Muestreo                                                                                                  2611 non-null int64
Vivienda seleccionada                                                                                                        2611 non-null int64
Consecutivo del hogar en la vivienda                                                                                         2611 non-null int64
Consecutivo del residente habitual miembro del hogar                                                                         2611 non-null int64
nan                                                                                                                          2611 non-null float64
Clave Llave única para cada migrante internacional delcalrado en el hogar en la base (UPM+VIV_SEL+HOGAR+N_REN)               872 non-null float64
Clave única de identificación del hogar (UPM+VIV_SEL+ HOGAR)                                                                 2611 non-null int64
Clave única de identificación de la vivienda (UPM+VIV_SEL+HOGAR)                                                             2611 non-null int64
Clave de Entidad Federativa de levantamiento de la información                                                               2611 non-null object
Clave de tamaño de localidad                                                                                                 2611 non-null object
P4.4 Cuando (NOMBRE) se fue la última vez, ¿vivía con ustedes?                                                               2611 non-null object
P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?                                                          2611 non-null object
P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otra entidad)                                          2347 non-null object
P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otro país)                                             36 non-null object
P4.6 (NOMBRE) es hombre o mujer                                                                                              2611 non-null object
P4.7 ¿Qué es (NOMBRE) de la jefa o jefe del hogar?                                                                           2611 non-null object
P4.7 ¿Qué es (NOMBRE) de la jefa o jefe del hogar? (Otro parentesco)                                                         296 non-null object
P4.8 La última vez que (NOMBRE) se fue, ¿cuántos años cumplidos tenía?                                                       2611 non-null int64
P4.9 La última vez que (NOMBRE) se fue a vivir a otro país, ¿en qué estado de la República Mexicana vivía?                   2609 non-null object
P4.9 La última vez que (NOMBRE) se fue a vivir a otro país, ¿en qué estado de la República Mexicana vivía? (Otra entidad)    38 non-null object
P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Mes)                                             2611 non-null object
P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año)                                             2611 non-null int64
P4.11 ¿A qué país se fue (NOMBRE) la última vez?                                                                             2611 non-null object
P4.11 ¿A qué país se fue (NOMBRE) la última vez? (Otro país)                                                                 2611 non-null object
P4.12 ¿A qué estado de EUA llegó (NOMBRE) a vivir (la última vez)?                                                           2289 non-null object
P4.12C ¿A qué estado de EUA llegó (NOMBRE) a vivir (la última vez)? (Otro estado)                                            819 non-null object
P4.13 Cuando (NOMBRE) se fue la última vez, ¿qué tipo de documento llevaba?                                                  2289 non-null object
P4.14 ¿Cuál fue el motivo principal por el que (NOMBRE) se fue la última vez?                                                2611 non-null object
P4.14A ¿Se fue a buscar trabajo? ¿Con trabajo?                                                                               0 non-null object
nan                                                                                                                          122 non-null object
P4.15 ¿En qué país vive actualmente (NOMBRE)?                                                                                2611 non-null int64
P4.15 ¿En qué país vive actualmente (NOMBRE)? (Otro país)                                                                    1629 non-null object
P4.16 ¿En qué estado de EUA vive actualmente (NOMBRE)?                                                                       1491 non-null object
nan                                                                                                                          1487 non-null object
P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía?                                               961 non-null object
P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía? (Otro estado)                                 330 non-null object
P4.17 Cuando (NOMBRE) se regresó a México, ¿en qué estado de EUA o país vivía? (Otro país)                                   185 non-null object
P4.18 ¿En qué mes y año regresó (NOMBRE) a vivir a la República Mexicana? (Mes)                                              961 non-null object
P4.18 ¿En qué mes y año regresó (NOMBRE) a vivir a la República Mexicana? (Año)                                              961 non-null float64
P4.19 ¿Cuál fue el motivo principal por el que (NOMBRE) se regresó?                                                          961 non-null object
P4.19 ¿Cuál fue el motivo principal por el que (NOMBRE) se regresó? (Otro motivo)                                            179 non-null object
P4.20 (NOMBRE) actualmente forma parte de este hogar?                                                                        961 non-null object
P4.20 Número de renglón en la lista de personas                                                                              872 non-null float64
Factor de expansión a nivel vivienda                                                                                         2611 non-null int64
Tamaño de localidad, segunda agrupación                                                                                      2611 non-null object
Tamaño de localidad, tercera agrupación                                                                                      2611 non-null object
P4.8.AG1 Edad al emigrar ( grupos quinquenales)                                                                              2611 non-null object
P4.8.AG2 Edad al emigrar por grandes grupos                                                                                  2611 non-null object
Condición de tenencia de documento para ingresar a EUA                                                                       2289 non-null object
Condición de retorno a México                                                                                                2611 non-null object
Duración de migración (en meses)                                                                                             961 non-null float64
Duración de migración (agrupado)                                                                                             911 non-null object
Estrato sociodemográfico                                                                                                     2611 non-null object
Estrato de diseño muestral                                                                                                   2611 non-null int64
Unidad Primaria de Muestreo                                                                                                  2611 non-null int64
dtypes: float64(5), int64(12), object(38)
memory usage: 1.1+ MB

In [115]:
datos_migrante.pivot_table(
    index = 'P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año)',
    columns = 'P4.11 ¿A qué país se fue (NOMBRE) la última vez?',
    values = 'Factor de expansión a nivel vivienda',
    aggfunc = 'sum',
    margins = True,
    margins_name = 'Totales',
)

P4.11 ¿A qué país se fue (NOMBRE) la última vez?,Estados Unidos de América,Otro país,Totales
P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año),,,
2013,39544,10016,49560
2014,66044,9044,75088
2015,80476,16789,97265
2016,111777,22111,133888
2017,129152,22791,151943
2018,208671,33908,242579
9999,9794,662,10456
Totales,645458,115321,760779

In [121]:
datos_migrante.pivot_table(
    columns = 'P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año)',
    index = 'P4.11 ¿A qué país se fue (NOMBRE) la última vez? (Otro país)',
    values = 'Factor de expansión a nivel vivienda',
    aggfunc = 'sum',
    margins = True,
    margins_name = 'Totales',
    fill_value = ''
)

P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año),2013,2014,2015,2016,2017,2018,9999,Totales
P4.11 ¿A qué país se fue (NOMBRE) la última vez? (Otro país),,,,,,,,
ARGENTINA,,111,791,883,832,917,,3534
BARBADOS,,,,1532,,,,1532
BELICE,,,,,189,,,189
CANADA,3874,1288,1234,2977,7460,12941,475,30249
COMMONWEALTH DE AUSTRALIA,,,124,391,148,,,663
CONFEDERACION SUIZA,,,,,99,,,99
EMIRATOS ARABES UNIDOS,,678,200,342,,,,1220
ESTADO DE ISRAEL,,,,345,,1108,,1453
ESTADO DE JAPON,,,,,499,,,499
ESTADOS UNIDOS DE AMERICA,39544,66044,80476,111777,129152,208671,9794,645458
EUROPA,,,,1251,195,778,,2224
FEDERACION DE RUSIA,,,,,677,,,677
NUEVA ZELANDA,368,,,,,480,,848
PAIS NO ESPECIFICADO,,614,,67,301,,,982
REINO DE BELGICA,695,,,,,,,695
REINO DE DINAMARCA,,,,,610,,,610
REINO DE ESPAÑA,2499,2133,2057,3266,1914,5170,,17039
REINO DE LOS PAISES BAJOS,,,1203,,,,,1203
REINO DE TAILANDIA,89,,,299,107,,,495
REINO UNIDO DE GRAN BRETAÑA E IRLANDA,,1185,1075,1451,869,1825,,6405
REPUBLICA DE AUSTRIA,,,488,,,,,488
REPUBLICA DE CHILE,,,117,,,,,117
REPUBLICA DE COLOMBIA,,219,,55,256,736,,1266
REPUBLICA DE COSTA RICA,,77,,,,,,77
REPUBLICA DE CUBA,,,61,134,,,,195
REPUBLICA DE EL SALVADOR,,,184,,,,,184
REPUBLICA DE GUATEMALA,,,107,,399,,,506
REPUBLICA DE HONDURAS,,,512,,372,1391,,2275
REPUBLICA DE KAZAJSTAN,,,,,,89,,89
REPUBLICA DE KENIA,,,832,,,,,832
REPUBLICA DE LETONIA,,,,,875,,,875
REPUBLICA DE NICARAGUA,,,356,115,,,,471
REPUBLICA DE PANAMA,,87,1487,,,1608,,3182
REPUBLICA DE PERU,,672,,,,2351,,3023
REPUBLICA DE SUDAFRICA,1520,,,,,,,1520
REPUBLICA DEL ECUADOR,,,,2202,,,,2202
REPUBLICA DOMINICANA,,,,518,,,,518
REPUBLICA FEDERAL DE ALEMANIA,172,217,1309,2802,2696,364,187,7747
REPUBLICA FEDERATIVA DE BRASIL,,352,4366,162,454,473,,5807
REPUBLICA FRANCESA,,508,,3319,2692,2067,,8586
REPUBLICA ITALIANA,,335,,,451,875,,1661
REPUBLICA LIBANESA,430,,,,,,,430
REPUBLICA POPULAR CHINA,369,160,160,,603,484,,1776
REPUBLICA PORTUGUESA,,408,,,,251,,659
RUMANIA,,,,,93,,,93
UCRANIA,,,126,,,,,126
Totales,49560,75088,97265,133888,151943,242579,10456,760779

### Especificamente solo nacidos en MX

In [143]:
datos_migrante.groupby("P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otro país)")['Factor de expansión a nivel vivienda'].sum()

P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otro país)
BELICE                                    185
CANADA                                   5204
COMMONWEALTH DE AUSTRALIA                 148
CONFEDERACION SUIZA                        99
ESTADO LIBRE ASOCIADO DE PUERTO RICO      461
PAIS NO ESPECIFICADO                      508
REINO DE ESPAÑA                          3698
REINO UNIDO DE GRAN BRETAÑA E IRLANDA     741
REPUBLICA DE COSTA RICA                    77
REPUBLICA DE CUBA                         316
REPUBLICA DE GUATEMALA                    589
REPUBLICA DE HONDURAS                    2109
REPUBLICA DE KENIA                        416
REPUBLICA DE LETONIA                      875
REPUBLICA FEDERAL DE ALEMANIA             192
REPUBLICA FRANCESA                        875
Name: Factor de expansión a nivel vivienda, dtype: int64

In [145]:
datos_migrantes_mexicanos = datos_migrante[datos_migrante['P4.5 ¿En qué estado de la República Mexicana o país nació (NOMBRE)?  (Otro país)'].isna()].copy()

In [147]:
datos_migrantes_mexicanos.to_csv(DATOS_PROCESADOS / 'migrantes_mexicanos.csv', encoding = 'utf-8', index = False,)

In [149]:
migrante_por_año_por_pais = datos_migrantes_mexicanos.groupby(['P4.11 ¿A qué país se fue (NOMBRE) la última vez? (Otro país)', 'P4.10 ¿En qué mes y año se fue a vivir (NOMBRE) a otro país la última vez? (Año)'])['Factor de expansión a nivel vivienda'].sum().to_frame()

In [150]:
migrante_por_año_por_pais.to_csv(DATOS_PROCESADOS / 'migrante_por_año_por_pais.csv', encoding = 'utf-8',)

## Ver datos ipums

In [123]:
# arbol(DATOS_BRUTOS)

In [124]:
import gzip

In [125]:
with gzip.open(DATOS_BRUTOS / 'usa_00056.dta.gz',) as file:
    data_ipums = pd.read_stata(file)

In [127]:
data_ipums.head().T

,0,1,2,3,4
year,2017,2017,2017,2017,2017
datanum,1,1,1,1,1
serial,1,2,3,3,3
cbserial,2.017e+12,2.017e+12,2.017e+12,2.017e+12,2.017e+12
hhwt,206,45,136,136,136
statefip,alabama,alabama,alabama,alabama,alabama
countyfip,0,0,0,0,0
gq,households under 1970 definition,households under 1970 definition,households under 1970 definition,households under 1970 definition,households under 1970 definition
pernum,1,1,1,2,3
perwt,206,45,136,121,111
sex,male,female,male,female,male
age,73,31,41,48,16
bpl,alabama,georgia,georgia,illinois,alabama
bpld,alabama,georgia,georgia,illinois,alabama
citizen,n/a,n/a,n/a,n/a,n/a
yrnatur,n/a,n/a,n/a,n/a,n/a
yrimmig,0,0,0,0,0
yrsusa1,0,0,0,0,0
yrsusa2,n/a,n/a,n/a,n/a,n/a
language,english,english,english,english,english
languaged,english,english,english,english,english
speakeng,"yes, speaks only english","yes, speaks only english","yes, speaks only english","yes, speaks only english","yes, speaks only english"
educ,"grade 5, 6, 7, or 8",4 years of college,grade 12,grade 12,grade 10
educd,grade 7,bachelor's degree,ged or alternative credential,regular high school diploma,grade 10
empstat,not in labor force,employed,employed,not in labor force,not in labor force
empstatd,not in labor force,at work,at work,not in labor force,not in labor force
labforce,"no, not in the labor force","yes, in the labor force","yes, in the labor force","no, not in the labor force","no, not in the labor force"
occ,0,350,6260,0,0
ind,0,8090,770,0,0
migrate1,same house,same house,same house,same house,same house
migrate1d,same house,same house,same house,same house,same house
migplac1,n/a,n/a,n/a,n/a,n/a
migcounty1,0,0,0,0,0

In [128]:
ipums_mex = data_ipums[data_ipums['bpld'] == 'mexico']

In [129]:
ipums_mex.shape

(90222, 33)

In [133]:
ipums_mex = ipums_mex[ipums_mex['yrsusa1'] <= 1]

In [136]:
ipums_mex.groupby(["yrsusa1", 'migrate1'])['perwt'].sum()

yrsusa1  migrate1
0        n/a                       8721.0
         same house               47791.0
         moved within state        7161.0
         moved between states      1140.0
         abroad one year ago      47189.0
1        n/a                       3519.0
         same house              130980.0
         moved within state       36684.0
         moved between states      2956.0
         abroad one year ago      41553.0
Name: perwt, dtype: float64